# GitHub Actionsの名前
name: AutoBuild
# GitHub Actionsを実行させたい動作
on:
  # 今回はpush時に実行させる 
  push: 
# 自動化
jobs:
  build:
    runs-on: windows-latest
    steps:
      # プロジェクトをチェックアウトする
      - name: checkout
        uses: actions/checkout@v2
     # .Net のRuntimeを仮想OSにインストールする
    - name: Setup .NET
      uses: actions/setup-dotnet@v7
      with:
        dotnet-version: 7.0.0
    # プロジェクトで必要なライブラリなどをインストールする
    - name: Restore dependencies
      run: dotnet restore
    # ビルドを行う(同時にコーティング規約の静的チェックを行う)
    - name: DotNet Build Restore
      run: dotnet build --configuration Release
